"""
parse_course_content.py
-----------------------
Parses course exam PDFs and DOCX files from the /exam folder,
chunks the text, and writes seed_chunks.sql for D1 import.

Usage:
    pip install pypdf python-docx
    python3 scripts/parse_course_content.py

Output:
    backend/seed_chunks.sql  (overwritten each run)

To add a new course or file:
    1. Drop the PDF/DOCX into backend/exam/
    2. Add an entry to COURSE_FILES below
    3. Re-run this script
    4. Run:  npm run db:seed          (local)
             npm run db:seed:remote   (Cloudflare)
"""

import re
import os
import sys

try:
    import pypdf
except ImportError:
    sys.exit("Missing pypdf — run: pip install pypdf")

try:
    import docx
except ImportError:
    sys.exit("Missing python-docx — run: pip install python-docx")

# ── Configuration ─────────────────────────────────────────────────────────────
# Each entry: (class_id, class_name, filename)
# class_id must match what's in the classes table (see schema.sql)

EXAM_DIR = os.path.join(os.path.dirname(__file__), '..', 'exam')
OUTPUT   = os.path.join(os.path.dirname(__file__), '..', 'seed_chunks.sql')

COURSE_FILES = [
    (1, 'EECS 485', 'eecs485f25_final_solutions.pdf'),
    (1, 'EECS 485', 'eecs485f25_midterm_solutions.pdf'),
    (2, 'EECS 370', '370 F24 Final Solutions v2 (Public).docx'),
    (2, 'EECS 370', '370Midterm F24 - Answer Key.docx'),
]

# ── Extraction ────────────────────────────────────────────────────────────────

def extract_pdf(path):
    reader = pypdf.PdfReader(path)
    return '\n'.join(page.extract_text() or '' for page in reader.pages)

def extract_docx(path):
    doc = docx.Document(path)
    parts = [p.text.strip() for p in doc.paragraphs if p.text.strip()]
    for table in doc.tables:
        for row in table.rows:
            for cell in row.cells:
                if cell.text.strip():
                    parts.append(cell.text.strip())
    return '\n'.join(parts)

def extract(path):
    if path.endswith('.pdf'):
        return extract_pdf(path)
    elif path.endswith('.docx'):
        return extract_docx(path)
    else:
        raise ValueError(f"Unsupported file type: {path}")

# ── Cleaning ──────────────────────────────────────────────────────────────────

def clean(text):
    text = re.sub(r'uniqname:.*', '', text)
    text = re.sub(r'Licensed under.*', '', text)
    text = re.sub(r'https?://\S+', '', text)
    text = re.sub(r'Page \d+ of \d+', '', text)
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)
    return text.strip()

# ── Chunking (sliding window over words) ──────────────────────────────────────

def sliding_chunks(text, size=600, step=400, min_len=100):
    words = text.split()
    chunks = []
    i = 0
    while i < len(words):
        chunk = ' '.join(words[i:i + size])
        if len(chunk) >= min_len:
            chunks.append(chunk)
        i += step
    return chunks

# ── SQL escaping ──────────────────────────────────────────────────────────────

def esc(s):
    return s.replace("'", "''")

# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    # Collect unique class ids and names
    class_defs = {}
    for class_id, class_name, _ in COURSE_FILES:
        class_defs[class_id] = class_name

    all_chunks = []  # list of (class_id, chunk_text)

    for class_id, class_name, filename in COURSE_FILES:
        path = os.path.join(EXAM_DIR, filename)
        if not os.path.exists(path):
            print(f"  WARNING: file not found, skipping — {filename}")
            continue
        print(f"  Parsing {filename} ...", end=' ')
        raw = extract(path)
        cleaned = clean(raw)
        chunks = sliding_chunks(cleaned)
        all_chunks.extend((class_id, c) for c in chunks)
        print(f"{len(chunks)} chunks")

    # Build SQL
    lines = [
        '-- Auto-generated by scripts/parse_course_content.py',
        '-- DO NOT edit manually — re-run the script instead.',
        '',
    ]

    # Classes
    class_values = ', '.join(f"({cid}, '{cname}')" for cid, cname in class_defs.items())
    lines.append(f"INSERT OR IGNORE INTO classes (id, name) VALUES {class_values};")
    lines.append('')

    # Delete old chunks so re-runs don't duplicate
    lines.append('DELETE FROM course_chunks;')
    lines.append('')

    # Chunks
    for class_id, chunk in all_chunks:
        lines.append(f"INSERT INTO course_chunks (class_id, content) VALUES ({class_id}, '{esc(chunk)}');")

    sql = '\n'.join(lines)
    with open(OUTPUT, 'w', encoding='utf-8') as f:
        f.write(sql)

    print(f"\nDone. {len(all_chunks)} total chunks written to seed_chunks.sql")
    print("Next steps:")
    print("  Local:      npm run db:seed")
    print("  Cloudflare: npm run db:seed:remote")

if __name__ == '__main__':
    print(f"Exam directory: {os.path.abspath(EXAM_DIR)}")
    print(f"Output file:    {os.path.abspath(OUTPUT)}")
    print()
    main()
